name: steamworks_gen
description: A command-line tool to generate Steamworks SDK in a darty way
version: 0.4.4
homepage: https://github.com/aeb-dev/steamworks_gen
repository: https://github.com/aeb-dev/steamworks_gen
issues: https://github.com/aeb-dev/steamworks_gen/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.7.0
  cli_util: ^0.4.2
  ffi: ^2.1.4
  path: ^1.9.1
  recase: ^4.0.0

dev_dependencies:
  aeb_lint: ^1.1.0
  test: ^1.28.0

platforms:
  android:
  linux:
  macos:
  windows:
